// insert auth token below
@token = <add your JWT token here>

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "author": "comment 1",
  "title": "comment 1",
  "url": "comment 1",
  "likes": 2,
  "comments": ["Great post!", "Very informative."]
}