// insert auth token below
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2OTdjODkyNGJiNzdjNzFhNDlkYmRjZDQiLCJpYXQiOjE3Njk3Njk2ODYsImV4cCI6MTc2OTc3MzI4Nn0.iYc0k3jO3bjbs8J8w8Nd-hpdmzksgtRCLXixfQbrLuc

DELETE http://localhost:3001/api/blogs/697c8c4fbb77c71a49dbdd01
Authorization: Bearer {{token}}