@token = <add your JWT token here>

POST http://localhost:3001/api/blogs/697c8641bb77c71a49dbdcb7/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "Thanks for sharing this blog!"
}
